<These_are_supported_funding_model_platforms>
<github:[NickeManarin]
<patreon:nicke>
<open_collective:Replace_with_a_single_Open_Collective_username>
<ko_fi:nickemanarin>
<tidelift:Replace_with_a_ingle_Tidelift_platform_name/package-name_e_g_npm/babel>
<community_bridge:Replace_with_a_single_Community_Bridge_project_name_e_g_cloud-foundry>
<liberapay:Replace_with_a_single_Liberapay_username>
<issuehunt:NickeManarin>
<otechie:Replace_with_a_single_Otechie_username>
<custom:[https://www_screentogif_com/donate/https://flattr_com/NickeManarin/domain/screentogif_com/https//www_buymeacoffee_com/NickeManarin>
